### ISSUE TITLE
部分图片未加载 网页版1.3 -1小节开头部分  #bug#

### ISSUE THREAD

**Issue by Spike99** [datawhalechina/dive-into-cv-pytorch#12]
实际图片如下图, 未加载**不限于此小节**, **前1.1节也碰到类似状况**

![图片](https://user-images.githubusercontent.com/44233106/128699300-58e087f4-fa77-4819-b8c8-5b8d96d529e5.png)

**Comment by monkeyDemon** [comment]
感谢你的反馈，我刚确认了一下，目前教程中图片链接统一使用github的域名，github域名的图片确实经常存在裂图的问题，并非教程本身的bug。
![image](https://user-images.githubusercontent.com/24189709/130309490-40eb5879-f9de-4ec1-a775-e287581dcb0e.png)

请尝试查询类似“github图片无法打开”的解决方案，例如：https://blog.csdn.net/u011583927/article/details/104384169?spm=1001.2014.3001.5501
如仍无法解决，可尝试 科 学 上 网 的方式解决。
现将问题关闭，如仍有疑问，随时沟通
