### ISSUE TITLE
Recommend using jupyter notebook instead of markdown

### ISSUE THREAD

**Issue by ysl2** [datawhalechina/dive-into-cv-pytorch#14]
Hi, thanks for your significant work. Some bugs may not be found if you use markdown, so I was wondering if you could use jupyter notebook? Thanks!

**Comment by monkeyDemon** [comment]
感谢您的建议。 
由于我们使用docsify生成在线文档，所以教程需要是markdown的。code目录下有对应每一章节的源码，对应的py脚本都是确认过的，如果有遗漏的问题或bug，欢迎随时反馈。
目前项目还不完整，由于精力有限，我会优先进行新章节的编写。后面如果有时间了，并且有更多的人有相似的对于notebook的需求，我们会考虑用py和notebook两种方式提供代码。
由于不是代码问题的 issue，我就先关闭了。
