### ISSUE TITLE
代码拼写错误

### ISSUE THREAD

**Issue by Saminey** [datawhalechina/dive-into-cv-pytorch#26]
3.2.md文件中的transform函数中 resize处是不是漏掉了FT，应该改为FT.resize
![屏幕截图 2024-09-28 163633](https://github.com/user-attachments/assets/69be65e3-6908-4479-90b7-490e1f6e9327)

**Comment by UchihaBaiQing** [comment]
邮件已收到，祝好！

**Comment by Saminey** [comment]
utils.py文件中已定义resize函数，疑问终结，早知道提前看一下utils.py了
![屏幕截图 2024-09-28 165621](https://github.com/user-attachments/assets/90460a65-9291-4fda-b50b-4ef271623584)

**Comment by UchihaBaiQing** [comment]
邮件已收到，祝好！
