### ISSUE TITLE
第一、二章问题建议收集

### ISSUE THREAD

**Issue by monkeyDemon** [datawhalechina/dive-into-cv-pytorch#8]
大家好，我是datawhale成员安晟，也是本项目《动手学CV-pytorch版》的组织者。经过CV小组几周的努力，我们初步完成了前两章内容的构建。内容涉及环境安装、pytorch基本使用、CNN基本概念，分类问题实战等较基础的知识点。

我们希望能够更好的发扬datawhale的开源精神，帮助到有决心有动力想要进入CV领域的入门者。同时，项目还处于初期阶段，不免会有各种不够完美的地方，因此非常希望听听大家的意见建议，尤其是入门学习者的声音。

如果你刚刚入门CV，或者正在参加我们组织的《零基础入门CV赛事- 街景字符编码识别》新人赛，非常希望大家将本项目的内容当作学习材料，并且把在学习中遇到的问题，发现的我们的教程不全面，不细致的部分指出，帮助我们更好的输出优质内容。

因此，我发布了本次活动：

- 大家可以在本issue下发表评论，指出你的意见和改进建议。点赞最多的两个评论将会获得我本人赞助的大红包一个或深度学习优质书籍一本~

- 同时，大家也可以评论指出你认为写的最好的章节，来支持内容创作者，同样获得认可(点赞)最多章节的主要作者也会获得我本人赞书的红包一个~

期待大家积极响应，活动截至时间2020/6/5日晚12点。
注：获得奖励的前提是评论必须为有建设性的意见和建议，恶意刷赞是禁止的。平票时将会由本项目组成员根据评论质量来决定奖品归属。

**Comment by GYHHAHA** [comment]
看到项目预计分为三个阶段，在入门篇的部分个人感觉现在的内容已经足够好了，结合比赛的实际操作，确实能够对分类的问题和常规操作建立一些大局概念，下面提一些问题/建议：
1. 中级篇的动手实践和入门阶段的有哪些区别？例如，因为是介绍各个领域的细分内容，必然会重新提到图像的分类问题（分类应该算一个子领域吧），到时候会引入哪些新的知识点？or举办难度更大的比赛？
2. 在组织中级篇的时候，可以考虑和“competition-baseline”项目的内容进行交叉，这样在讲到某一个子任务的时候就能够找到对应的比赛，然后这样就能够通过了解这些比赛top的方案，反过来促进对这个子任务处理模式的理解。
3. 在高级篇，是否能有经典论文/源码的导读？分享的形式和周期大致是什么样？

**Comment by monkeyDemon** [comment]
> 看到项目预计分为三个阶段，在入门篇的部分个人感觉现在的内容已经足够好了，结合比赛的实际操作，确实能够对分类的问题和常规操作建立一些大局概念，下面提一些问题/建议：
> 
> 1. 中级篇的动手实践和入门阶段的有哪些区别？例如，因为是介绍各个领域的细分内容，必然会重新提到图像的分类问题（分类应该算一个子领域吧），到时候会引入哪些新的知识点？or举办难度更大的比赛？
> 2. 在组织中级篇的时候，可以考虑和“competition-baseline”项目的内容进行交叉，这样在讲到某一个子任务的时候就能够找到对应的比赛，然后这样就能够通过了解这些比赛top的方案，反过来促进对这个子任务处理模式的理解。
> 3. 在高级篇，是否能有经典论文/源码的导读？分享的形式和周期大致是什么样？

我个人的计划是在入门篇安排CV的三个通用领域的入门教程，分类，目标检测，图像分割。这块可以说是必须要掌握的内容。而在中级篇中安排细分领域的教程，不会再涉及分类这种，指的是比如图像检索，人脸识别，OCR，人体姿态预估这类细分领域的教程。因为涉及相当的专业性，具体形式和内容还要再看看大家的意见，以及结合团队成员自身的技术栈。

**Comment by monkeyDemon** [comment]
看来这种活动形式不太合适，大家参与不是很积极，之后会考虑其它形式，不在github上。
@GYHHAHA 看到可以联系我下~
